services:
  warehouse:
    image: postgres:14
    container_name: tokendb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"

  pipelinerunner:
    image: defi_pipeline
    container_name: defi_pipeline
    build:
      context: ./
      dockerfile: ./containers/pipeline/Dockerfile
    volumes:
      - ./:/code
    environment:
      WAREHOUSE_USER: ${POSTGRES_USER}
      WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
      DEFI_BD: ${POSTGRES_DB}
      WAREHOUSE_HOST: ${POSTGRES_HOST}
      WAREHOUSE_PORT: ${POSTGRES_PORT}

  dashboard:
    image: metabase/metabase
    container_name: dashboard
    ports:
      - "3000:3000"